package com.trustpay.account.domaine.exception;

public enum ErrorType {
  INVALID_ID,
  INVALID_EMAIL,
  INVALID_PHONE_NUMBER,
  INVALID_PASSWORD,

  MISSING_PASSWORD,

  DUPLICATE_EMAIL,
  DUPLICATE_PHONE_NUMBER,

  AUTHENTICATION_NOT_ALLOWED,
  PASSWORD_CHANGE_NOT_ALLOWED,

  UNSUPPORTED_AUTH_METHOD,
  UNSUPPORTED_AUTH_PROVIDER,
}
